name: Child

on:
  workflow_call:
    inputs:
      github_sha:
        required: true
        type: string
    secrets:
      some_secret:
        required: false
jobs:
  first:
    runs-on: ubuntu-latest

    steps:
      - name: Echo param
        run: echo ${{ inputs.github_sha }}
      
      - name: Echo secret
        run: echo ${{ secrets.SOME_SECRET }}

