name: Parent

on:
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  second:
    uses: epamemail/reusable_workflow/.github/workflows/reusable-workflow-child.yml@main
    with:
      github_sha: $GITHUB_SHA
#     secrets:
#       some_secret: ${{ secrets.SOME_SECRET }}
